CREATE TABLE app_user (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT uk_app_user_username UNIQUE (user_name),
    CONSTRAINT uk_app_user_email UNIQUE (email)
);

CREATE TABLE einkaufsladen (
    einkaufsladen_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT uk_einkaufsladen_name UNIQUE (name)
);

CREATE TABLE kategorie (
    kategorie_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT uk_kategorie_name UNIQUE (name)
);

CREATE TABLE lebensmittel (
    lebensmittelid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kategorie_id INTEGER NOT NULL,

    CONSTRAINT uk_lebensmittel_name UNIQUE (name),
    CONSTRAINT fk_food_category
        FOREIGN KEY (kategorie_id)
        REFERENCES kategorie (kategorie_id)
);

CREATE TABLE rezept (
    rezept_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beschreibung VARCHAR(255) NOT NULL,
    bild VARCHAR(255),
    leckerheitsskala INTEGER NOT NULL,
    dauer INTEGER NOT NULL,
    personen INTEGER NOT NULL
);

CREATE TABLE einkaufsladen_lebensmittel (
    einkaufsladen_lebensmittel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lebensmittel_id INTEGER NOT NULL,
    einkaufsladen_id INTEGER NOT NULL,
    preis DOUBLE PRECISION NOT NULL,

    CONSTRAINT uk_einkaufsladen_lebensmittel_laden_leb
        UNIQUE (einkaufsladen_id, lebensmittel_id),

    CONSTRAINT fk_einkaufsladen_lebensmittel_lebensmittel
        FOREIGN KEY (lebensmittel_id)
        REFERENCES lebensmittel (lebensmittelid),

    CONSTRAINT fk_einkaufsladen_lebensmittel_einkaufsladen
        FOREIGN KEY (einkaufsladen_id)
        REFERENCES einkaufsladen (einkaufsladen_id)
);

CREATE TABLE rezeptlebensmittel (
    rezept_lebensmittel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lebensmittel_id INTEGER NOT NULL,
    rezept_id INTEGER NOT NULL,
    menge DOUBLE PRECISION NOT NULL,
    einheit VARCHAR(255) NOT NULL,

    CONSTRAINT uk_rezeptlebensmittel_rezept_lebensmittel
        UNIQUE (rezept_id, lebensmittel_id),

    CONSTRAINT fk_rezeptlebensmittel_lebensmittel
        FOREIGN KEY (lebensmittel_id)
        REFERENCES lebensmittel (lebensmittelid),

    CONSTRAINT fk_rezeptlebensmittel_rezept
        FOREIGN KEY (rezept_id)
        REFERENCES rezept (rezept_id)
        ON DELETE CASCADE
);

CREATE TABLE "verfügbarelebensmittel" (
    verfuegbare_lebensmittel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lebensmittel_id INTEGER NOT NULL,
    anzahl DOUBLE PRECISION NOT NULL,
    threshold INTEGER NOT NULL,

    CONSTRAINT "uk_verfügbarelebensmittel_lebensmittel"
        UNIQUE (lebensmittel_id),

    CONSTRAINT fk_food_lebensmittel
        FOREIGN KEY (lebensmittel_id)
        REFERENCES lebensmittel (lebensmittelid)
);